version: 0.0
os: linux
hooks:
  AfterAllowTraffic:
    - location: scripts/health_check.sh
      timeout: 300
      runas: root
      onFailure: CONTINUE
    - location: scripts/rollback.sh
      timeout: 300
      runas: root
      onFailure: CONTINUE